stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: juniper
      pushRemote: true
      registry: 127.0.0.1:34088
timeout: 60
notification: {}
